pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    openssl s_client -showcerts -connect dap-master2.cyberarkdemo:443 < /dev/null 2> /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > dap-cert.pem

#- task: DownloadSecureFile@1
#  name: conjurCert
#  displayName: 'Download CA certificate'
#  inputs:
#    secureFile: 'conjur-dev.pem'

- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: '$(conjur-appliance-url)'
    conjuraccount: '$(conjur-account)'
    conjurusername: $(conjur-username)'
    conjurapikey: '$(API_KEY)'
    ignoreSsl: true

- bash: |
    cat $(conjurCert.secureFilePath) > $(CONJUR_CERT_FILE)
    echo "Secrets retrieved:"
    echo "  DB_UNAME: $(DB_UNAME) > leaked_secrets.txt"
    echo >> leaked_secrets.txt 
    echo "  DB_PWD: $(DB_PWD) >> leaked_secrets.txt"
    cat leaked_secrets.txt
